-- $ curl -O https://15445.courses.cs.cmu.edu/fall2018/files/bike_sharing.tar.gz
-- $ tar -zxvf bike_sharing.tar.gz
-- $ sqlite3 bike_sharing.db < setup.sql
-- sqlite3 bike_sharing.db
-- sqlite> .tables
-- $ wget https://15445.courses.cs.cmu.edu/fall2018/files/placeholder.zip
-- $ unzip placeholder.zip
-- sqlite> .schema station